/**
 * Auto-Setup CLI for Antigravity WeChat Bridge
 * Fetches QR Code, renders in console/image, auto-writes .env, compiles, and registers autostart.
 */

import https from 'https';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const ILINK_BASE_URL = 'https://ilinkai.weixin.qq.com';
const BOT_TYPE = '3';

async function fetchQRCode(): Promise<{ qrcode: string; qrcode_img_content: string }> {
  const url = `${ILINK_BASE_URL}/ilink/bot/get_bot_qrcode?bot_type=${BOT_TYPE}`;
  const body = JSON.stringify({ local_token_list: [] });

  return new Promise((resolve, reject) => {
    const req = https.request(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body),
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) OpenClaw/1.0',
      },
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(new Error(`Failed to parse QR response: ${data}`));
        }
      });
    });

    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

async function pollStatus(qrcode: string, baseUrl: string = ILINK_BASE_URL): Promise<any> {
  const url = `${baseUrl}/ilink/bot/get_qrcode_status?qrcode=${encodeURIComponent(qrcode)}`;

  return new Promise((resolve, reject) => {
    const req = https.request(url, {
      method: 'GET',
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) OpenClaw/1.0',
      },
      timeout: 35000,
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(new Error(`Failed to parse status: ${data}`));
        }
      });
    });

    req.on('error', reject);
    req.on('timeout', () => {
      req.destroy();
      resolve({ status: 'wait' });
    });
    req.end();
  });
}

async function main() {
  console.log('\n============================================================');
  console.log('🤖 Antigravity WeChat Bridge 一键智能配置助手');
  console.log('============================================================\n');

  console.log('🔄 正在向腾讯微信官方请求专属绑定二维码...');
  try {
    const qrData = await fetchQRCode();
    const qrContent = qrData.qrcode_img_content || qrData.qrcode;
    const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=${encodeURIComponent(qrContent)}`;

    console.log('\n✅ 成功生成二维码！');
    console.log('🔗 扫码链接: ' + qrContent);
    console.log('\n📱 【请使用微信扫描下方二维码图片进行授权绑定】：');
    console.log('👉 ' + qrImageUrl + '\n');

    // Automatically try to open the browser for supreme user experience
    try {
      if (process.platform === 'win32') {
        execSync(`start "" "${qrImageUrl}"`);
      }
    } catch {}

    console.log('⏳ 正在等待手机微信扫码确认...');

    let currentBase = ILINK_BASE_URL;
    while (true) {
      const statusRes = await pollStatus(qrData.qrcode, currentBase);
      const st = statusRes.status;

      if (st === 'scaned') {
        console.log('📲 检测到已扫码，请在手机微信上点击【确认登录/绑定】...');
      } else if (st === 'confirmed') {
        console.log('\n🎉 微信授权绑定成功！');
        
        const botToken = statusRes.bot_token;
        const botId = statusRes.ilink_bot_id;
        const userId = statusRes.ilink_user_id;

        // Auto-generate .env
        const projectDir = path.dirname(__dirname);
        const envPath = path.join(projectDir, '.env');
        const envContent = [
          `# Auto-generated by Antigravity Setup Wizard`,
          `WECHAT_BOT_TOKEN=${botToken}`,
          `WECHAT_BOT_ID=${botId}`,
          `WECHAT_ALLOWED_USER=${userId}`,
          `WECHAT_BASE_URL=https://ilinkai.weixin.qq.com`,
          `PORT=53199`,
          `PREVENT_SLEEP=true`,
          `MAX_UPLOAD_BYTES=104857600`,
        ].join('\n');

        fs.writeFileSync(envPath, envContent, 'utf-8');
        console.log('💾 .env 配置文件已自动生成并保存！');

        console.log('⚙️ 正在自动配置开机自启与系统托盘...');
        try {
          execSync('python scripts/register-registry.py', { cwd: projectDir });
          console.log('✅ Windows 注册表自启已注入！');
        } catch {}

        console.log('\n🚀 正在启动后台网关服务...');
        try {
          if (process.platform === 'win32') {
            execSync('powershell -Command "Start-Process pythonw.exe -ArgumentList \'scripts/tray_companion.py\'"', { cwd: projectDir });
          }
          console.log('🟢 微信网关托盘伴侣已启动！电脑右下角已亮起绿灯！');
        } catch {}

        console.log('\n============================================================');
        console.log('🎊 全部配置已 100% 自动完成！');
        console.log('现在拿起手机打开微信，直接发送「会话」或「你好」即可畅享！');
        console.log('============================================================\n');
        break;
      } else if (st === 'expired') {
        console.log('⚠️ 二维码已过期，请重新运行一键配置命令。');
        break;
      } else if (st === 'scaned_but_redirect' && statusRes.redirect_host) {
        currentBase = `https://${statusRes.redirect_host}`;
      }

      await new Promise(r => setTimeout(r, 2000));
    }
  } catch (err: any) {
    console.error('❌ 配置过程出现异常:', err.message);
  }
}

main();
